## Reading Images in Python

We read images to python primarily for processing.
Processing on multidimensional data is easy with numpy arrays.

The two popular ways are using skimage or opencv.
skimage and opencv directly store imported images as numpy arrays.

There is also a Pillow library but it does not convert to numpy array by default.
Need to convert as a separate step... np.asarray(img)

### Using scikit-image

io.imread(file path)

 - to install scikit-image use pip install scikit-image
 - to import the package use import skimage

In [1]:
# Reading image using skimage

from skimage import io

img = io.imread(r"C:\Users\Owner\python\Datasets\Training\Fire\a.jpg")
# The variable is a numpy array of type unsigned integer of 8 bytes (uint8)

In [7]:
print(img)

[[[114  59   3]
  [116  61   5]
  [118  63   7]
  ...
  [250 178  32]
  [250 178  32]
  [250 178  32]]

 [[112  57   3]
  [113  58   4]
  [115  60   4]
  ...
  [252 177  32]
  [252 177  32]
  [252 177  32]]

 [[108  52   1]
  [109  53   2]
  [111  55   4]
  ...
  [250 175  30]
  [250 175  30]
  [250 175  30]]

 ...

 [[ 45  12   7]
  [ 49  16  11]
  [ 57  22  18]
  ...
  [  2   0   1]
  [  2   0   1]
  [  2   0   1]]

 [[ 55  15  13]
  [ 61  21  19]
  [ 68  29  24]
  ...
  [  2   0   1]
  [  2   0   1]
  [  2   0   1]]

 [[ 62  17  14]
  [ 65  20  17]
  [ 68  24  21]
  ...
  [  2   0   1]
  [  2   0   1]
  [  2   0   1]]]


In [2]:
print(type(img))
print(img.shape)    # (y,x,c)

# y - Height = 183
# x - Width = 275
# c = channels = 3 (RGB)

<class 'numpy.ndarray'>
(183, 275, 3)


In [3]:
# Some image processing tasks require floating point image with values between 0 and 1
# for this use function img_as_float of skimage

from skimage import img_as_float
img_float = img_as_float(img)

In [8]:
print(img_float)

[[[0.44705882 0.23137255 0.01176471]
  [0.45490196 0.23921569 0.01960784]
  [0.4627451  0.24705882 0.02745098]
  ...
  [0.98039216 0.69803922 0.1254902 ]
  [0.98039216 0.69803922 0.1254902 ]
  [0.98039216 0.69803922 0.1254902 ]]

 [[0.43921569 0.22352941 0.01176471]
  [0.44313725 0.22745098 0.01568627]
  [0.45098039 0.23529412 0.01568627]
  ...
  [0.98823529 0.69411765 0.1254902 ]
  [0.98823529 0.69411765 0.1254902 ]
  [0.98823529 0.69411765 0.1254902 ]]

 [[0.42352941 0.20392157 0.00392157]
  [0.42745098 0.20784314 0.00784314]
  [0.43529412 0.21568627 0.01568627]
  ...
  [0.98039216 0.68627451 0.11764706]
  [0.98039216 0.68627451 0.11764706]
  [0.98039216 0.68627451 0.11764706]]

 ...

 [[0.17647059 0.04705882 0.02745098]
  [0.19215686 0.0627451  0.04313725]
  [0.22352941 0.08627451 0.07058824]
  ...
  [0.00784314 0.         0.00392157]
  [0.00784314 0.         0.00392157]
  [0.00784314 0.         0.00392157]]

 [[0.21568627 0.05882353 0.05098039]
  [0.23921569 0.08235294 0.0745098 ]


In [5]:
#There is a function in numpy astype that sets the type of array as defined by astype
# but avoid using astype as it violates assumptions about dtype range.
# for example float should range from 0 to 1 (or -1 to 1) but if you use 
#astype to convert to float, the values do not lie between 0 and 1.

import numpy as np
img2 = img.astype(np.float)

In [9]:
print(img2)

[[[114.  59.   3.]
  [116.  61.   5.]
  [118.  63.   7.]
  ...
  [250. 178.  32.]
  [250. 178.  32.]
  [250. 178.  32.]]

 [[112.  57.   3.]
  [113.  58.   4.]
  [115.  60.   4.]
  ...
  [252. 177.  32.]
  [252. 177.  32.]
  [252. 177.  32.]]

 [[108.  52.   1.]
  [109.  53.   2.]
  [111.  55.   4.]
  ...
  [250. 175.  30.]
  [250. 175.  30.]
  [250. 175.  30.]]

 ...

 [[ 45.  12.   7.]
  [ 49.  16.  11.]
  [ 57.  22.  18.]
  ...
  [  2.   0.   1.]
  [  2.   0.   1.]
  [  2.   0.   1.]]

 [[ 55.  15.  13.]
  [ 61.  21.  19.]
  [ 68.  29.  24.]
  ...
  [  2.   0.   1.]
  [  2.   0.   1.]
  [  2.   0.   1.]]

 [[ 62.  17.  14.]
  [ 65.  20.  17.]
  [ 68.  24.  21.]
  ...
  [  2.   0.   1.]
  [  2.   0.   1.]
  [  2.   0.   1.]]]


In [6]:
# We can also convert floating point image to 8 bit unsigned int
# use skimage.img_as_ubyte to do so

from skimage import img_as_ubyte
img_8bit = img_as_ubyte(img_float)

In [10]:
print(img_8bit)

[[[114  59   3]
  [116  61   5]
  [118  63   7]
  ...
  [250 178  32]
  [250 178  32]
  [250 178  32]]

 [[112  57   3]
  [113  58   4]
  [115  60   4]
  ...
  [252 177  32]
  [252 177  32]
  [252 177  32]]

 [[108  52   1]
  [109  53   2]
  [111  55   4]
  ...
  [250 175  30]
  [250 175  30]
  [250 175  30]]

 ...

 [[ 45  12   7]
  [ 49  16  11]
  [ 57  22  18]
  ...
  [  2   0   1]
  [  2   0   1]
  [  2   0   1]]

 [[ 55  15  13]
  [ 61  21  19]
  [ 68  29  24]
  ...
  [  2   0   1]
  [  2   0   1]
  [  2   0   1]]

 [[ 62  17  14]
  [ 65  20  17]
  [ 68  24  21]
  ...
  [  2   0   1]
  [  2   0   1]
  [  2   0   1]]]


### Using openCV

cv2.imread(file path, color)

- to install openCV : pip install opencv-python
- to import the package : import cv2

In opencv we can import images in color, grey scale or unchanged using individual commands 
- cv2.IMREAD_COLOR : Loads a color image. Any transparency of image will be neglected. It is the default flag.
- cv2.IMREAD_GRAYSCALE : Loads image in grayscale mode
- cv2.IMREAD_UNCHANGED : Loads image as such including alpha channel

Instead of these three flags, you can simply pass integers 1, 0 or -1 respectively.

In [11]:
# images opened using opencv are also numpy arrays
import cv2

gray_image = cv2.imread(r"C:\Users\Owner\python\Datasets\Training\Fire\a.jpg", 0)
print(gray_image)

[[ 69  71  73 ... 183 183 183]
 [ 67  68  70 ... 183 183 183]
 [ 63  64  66 ... 181 181 181]
 ...
 [ 21  25  32 ...   1   1   1]
 [ 27  33  40 ...   1   1   1]
 [ 30  33  37 ...   1   1   1]]


In [12]:
color_image = cv2.imread(r"C:\Users\Owner\python\Datasets\Training\Fire\a.jpg", 1)
print(color_image)

[[[  3  59 114]
  [  5  61 116]
  [  7  63 118]
  ...
  [ 32 177 253]
  [ 32 177 252]
  [ 32 177 252]]

 [[  3  57 112]
  [  4  58 113]
  [  6  60 115]
  ...
  [ 32 177 253]
  [ 32 177 252]
  [ 32 177 252]]

 [[  1  53 106]
  [  2  54 107]
  [  4  55 111]
  ...
  [ 30 175 251]
  [ 30 175 250]
  [ 30 175 250]]

 ...

 [[  7  11  46]
  [ 11  15  50]
  [ 18  22  57]
  ...
  [  1   0   4]
  [  1   0   2]
  [  1   0   2]]

 [[ 13  15  55]
  [ 19  21  61]
  [ 24  29  68]
  ...
  [  1   0   4]
  [  1   0   2]
  [  1   0   2]]

 [[ 14  17  62]
  [ 17  20  64]
  [ 21  24  68]
  ...
  [  1   0   4]
  [  1   0   2]
  [  1   0   2]]]


In [13]:
print(type(gray_image))
print(gray_image.shape)
print(type(color_image))
print(color_image.shape)

<class 'numpy.ndarray'>
(183, 275)
<class 'numpy.ndarray'>
(183, 275, 3)


### Difference between skimage imread and opencv is that
### opencv reads images as BGR instead of RGB

In [14]:
# We can convert BGR image to RGB using COLOR_BGR2RGB

img_opencv = cv2.cvtColor(color_image, cv2.COLOR_BGR2RGB)
print(img_opencv)

[[[114  59   3]
  [116  61   5]
  [118  63   7]
  ...
  [253 177  32]
  [252 177  32]
  [252 177  32]]

 [[112  57   3]
  [113  58   4]
  [115  60   6]
  ...
  [253 177  32]
  [252 177  32]
  [252 177  32]]

 [[106  53   1]
  [107  54   2]
  [111  55   4]
  ...
  [251 175  30]
  [250 175  30]
  [250 175  30]]

 ...

 [[ 46  11   7]
  [ 50  15  11]
  [ 57  22  18]
  ...
  [  4   0   1]
  [  2   0   1]
  [  2   0   1]]

 [[ 55  15  13]
  [ 61  21  19]
  [ 68  29  24]
  ...
  [  4   0   1]
  [  2   0   1]
  [  2   0   1]]

 [[ 62  17  14]
  [ 64  20  17]
  [ 68  24  21]
  ...
  [  4   0   1]
  [  2   0   1]
  [  2   0   1]]]
